name: refcod
channels:
  - anaconda
  - defaults
dependencies:
  - pip:
    - torch==1.7.1
    - torchvision==0.8.2
    - opencv-python==3.4
    - opencv-contrib-python==3.4
    - scikit-learn
    - matplotlib
    - tqdm
    - tensorboard
    - tensorboardX
    
